### ISSUE TITLE
80% and 70% coverage glyph lists should differ but don't yet

### ISSUE THREAD

**Issue by EbenSorkin** [NeilSureshPatel/font-lang-support-afr#16]
seen on: https://jamrapatel.github.io/font-lang-support-afr/glyph-analysis.html

These seem identical and that doesn't seem quite right

80% Coverage:
a A b B c C d D e E f F g G h H i I j J k K l L m M n N o O p P q Q r R s S t T u U v V w W x X y Y z Z ɛ Ɛ ɔ Ɔ ŋ Ŋ

70% Coverage:
a A b B c C d D e E f F g G h H i I j J k K l L m M n N o O p P q Q r R s S t T u U v V w W x X y Y z Z ɛ Ɛ ɔ Ɔ ŋ Ŋ

**Comment by NeilSureshPatel** [comment]
This is the intended behavior. The plot is showing the the smallest glyph set needed to support the most languages. Therefore, 100% of languages are supported with the entire glyph set, since there are glyphs are are needed for only one language. The analysis is done by seeing which glyphs are needed for 10% of languages or more, then 20% or more , 30% or more , etc. As glyphs are encountered that are more exclusive to certain languages they bubble up to the higher percentage thresholds. What this means is that it is possible that the same glyphs are required for 70% of languages as are also required for 80% of languages. In other words, there is complete overlap between what is required for both 70% and 80% of languages.

**Comment by EbenSorkin** [comment]
I see - it is plateau. Ok thanks!
